name: Build Docker App Image and Push it to Docker Hub

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push app
        uses: docker/build-push-action@v4
        with:
          context: chrome/
          platforms: linux/arm64
          file: chrome/Dockerfile.alpine
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cimp-arm64:latest
